name: simple build and test

on:
  push:
    branches:
      - master
      - main
      - chore/test
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake libcyaml-dev libjson-c-dev libevent-dev lcov -y

      - name: Create makefile
        run: |
          cmake -S . -B $(pwd)/cmake-build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"
          cmake -S . -B $(pwd)/cmake-build -DCMAKE_BUILD_TYPE=Coverage

      - name: Build
        run: |
          cmake --build $(pwd)/cmake-build --config Release
          cmake --build $(pwd)/cmake-build

      - name: setup python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Run tests
        run: |
          cd caster-test
          ../cmake-build/caster -c caster_config/caster.yaml &
          CASTER_PID=$!
          pip install -r requirements.txt 
          behave
          kill -SIGINT $CASTER_PID

      #- name: Run tests
      #  run: |
      #    exec test
      #

      #- name: Generate coverage report
      #  run: |
      #    cd $(pwd)/cmake-build
      #    lcov --capture --directory . --output-file coverage.info
      #    lcov --remove coverage.info '/usr/*' --output-file coverage.info
      #    lcov --list coverage.info
      - name: Generate coverage report
        run: |
          cd $(pwd)/cmake-build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info
